### ISSUE TITLE
Error running examples

### ISSUE THREAD

**Issue by Millux** [nupic-community/nupic.studio#29] opened 2015-08-12 08:08 UTC
Hello Everibody,
    after the installation of  Nupic_sudio on Ubuntu 12.04, I tried to run the given examples. For each one I can initialize the nework with no problem, but if I try to do 1 step prediction (but for n-steps is the same) nothing changes in the net.

Looking at the console, when I click the prediction button I see this message:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nupic_studio-1.1.2-py2.7.egg/nupic_studio/ui/main_form.py", line 509, in __buttonStepHTM_Click
    Global.project.network.nextStep()
  File "/usr/local/lib/python2.7/dist-packages/nupic_studio-1.1.2-py2.7.egg/nupic_studio/htm/network.py", line 68, in nextStep
    node.nextStep()
  File "/usr/local/lib/python2.7/dist-packages/nupic_studio-1.1.2-py2.7.egg/nupic_studio/htm/node_region.py", line 277, in nextStep
    self.updateTemporalElements()
  File "/usr/local/lib/python2.7/dist-packages/nupic_studio-1.1.2-py2.7.egg/nupic_studio/htm/node_region.py", line 472, in updateTemporalElements
    (_, sourceCellAbsIdx, permanence) = self.temporalPooler.connections.dataForSynapse(synIdx)
TypeError: 'SynapseData' object is not iterable

Any idea?

**Comment by larvasapiens** [comment] 2015-09-21 23:16
I got the same error here. Were you able to solve this?

**Comment by rcrowder** [comment] 2015-09-22 12:21
@Millux @larvasapiens I may have found the cause of this. Just working out with Numenta engineers how to get around this. Will ping you both on a fix PR.

**Comment by larvasapiens** [comment] 2015-09-22 21:04
Thank you!

**Comment by Millux** [comment] 2015-09-23 06:08
Thank you Richard!

**Comment by rcrowder** [comment] 2015-10-09 11:52
The breaking change was introduced in this commit https://github.com/numenta/nupic/pull/2346/files#r40582664 Hopefully someone with Python knowledge can see a way to fix this.

**Comment by rcrowder** [comment] 2015-11-01 09:47
@Millux I've added a PR change that gets around the assert. I'm not familiar with using nupic.studio, so if you or @larvasapiens can check the change we can get it merged in. cc @rhyolight

**Closed** 2015-11-20 00:22 UTC
Labels: bug, in progress

**Comment by david-ragazzi** [comment] 2015-11-20 00:24
Hi @Millux @larvasapiens, I pull @rcrowder changes, could you push changes again? If not, you can pip too, but only this weekend..

**Comment by larvasapiens** [comment] 2015-11-20 02:30
It works now :smile:  :+1:

**Comment by iheddle** [comment] 2016-02-02 23:28
Hi David,
I've just pip installed nupic_studio and I'm getting the same error described by Millux: -

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nupic_studio/ui/main_form.py", line 509, in __buttonStepHTM_Click
    Global.project.network.nextStep()
  File "/usr/lib/python2.7/site-packages/nupic_studio/htm/network.py", line 68, in nextStep
    node.nextStep()
  File "/usr/lib/python2.7/site-packages/nupic_studio/htm/node_region.py", line 277, in nextStep
    self.updateTemporalElements()
  File "/usr/lib/python2.7/site-packages/nupic_studio/htm/node_region.py", line 472, in updateTemporalElements
    (_, sourceCellAbsIdx, permanence) = self.temporalPooler.connections.dataForSynapse(synIdx)
TypeError: 'SynapseData' object is not iterable

Should I be using github rather than pip to install this?

**Comment by ibexel** [comment] 2016-02-06 11:40
@iheddle I'm getting the exact same

**Comment by ibexel** [comment] 2016-02-06 14:06
@iheddle i fixed it by following the Developer instructions for nupic.studio installation, i guess the pip install doesn't have the latest code yet. I also followed the develop instructions to compile/install nupic.core, nupic.bindings and nupic itself, thinking those were the issue. But I think compiling nupic.studio is what fixed it.

**Comment by iheddle** [comment] 2016-02-07 06:55
Thanks for the feedback
